server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${APPLICATION_NAME}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}?characterEncoding=UTF8&userSSL=false
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  flyway:
    enabled: true

  jpa:
    show-sql: true
    generate-ddl: false

  config:
    import: optional:file:.env[.properties]
  mvc:
    path match:
      matching-strategy: ant_path_matcher